#!/bin/bash

function setDateUtil() {
  if [[ "$(uname)" =~ ^Darwin ]]; then 
    if [ -n "$(which gdate)" ]; then 
      echo "gdate"
    else
      echo "need gnu date: please install via homebrew" 1>&2
      exit 1
    fi
  else
    echo "date"
  fi
}

function getDaysOfWeek() {
  YEAR=$($DATEUTIL +%Y)
  WEEK=$1

  OUTPUT_DATE_FORMAT="%F"

  A_DAY_IN_FIRST_WEEK=$($DATEUTIL -d"$YEAR-01-04" +%w)
  DAYS_BEFORE_THE_DAY=$((( $A_DAY_IN_FIRST_WEEK + 6) % 7 ))
  MONDAY_IN_FIRST_WEEK=$($DATEUTIL -d"$YEAR-01-04 -$DAYS_BEFORE_THE_DAY days" +%F)

  MONDAY_IN_REQUESTED_WEEK=$($DATEUTIL -d"$MONDAY_IN_FIRST_WEEK $(( 7 * $WEEK - 7 )) days" "+$OUTPUT_DATE_FORMAT")
  TUESDAY_IN_REQUESTED_WEEK=$($DATEUTIL -d"$MONDAY_IN_FIRST_WEEK $(( 7 * $WEEK - 7 )) days +1 day" "+$OUTPUT_DATE_FORMAT")
  WEDNESDAY_IN_REQUESTED_WEEK=$($DATEUTIL -d"$MONDAY_IN_FIRST_WEEK $(( 7 * $WEEK - 7 )) days +2 day" "+$OUTPUT_DATE_FORMAT")
  THURSDAY_IN_REQUESTED_WEEK=$($DATEUTIL -d"$MONDAY_IN_FIRST_WEEK $(( 7 * $WEEK - 7 )) days +3 day" "+$OUTPUT_DATE_FORMAT")
  FRIDAY_IN_REQUESTED_WEEK=$($DATEUTIL -d"$MONDAY_IN_FIRST_WEEK $(( 7 * $WEEK - 7 )) days +4 day" "+$OUTPUT_DATE_FORMAT")
  SATURDAY_IN_REQUESTED_WEEK=$($DATEUTIL -d"$MONDAY_IN_FIRST_WEEK $(( 7 * $WEEK - 7 )) days +5 day" "+$OUTPUT_DATE_FORMAT")
  SUNDAY_IN_REQUESTED_WEEK=$($DATEUTIL -d"$MONDAY_IN_FIRST_WEEK $(( 7 * $WEEK - 7 )) days +6 day" "+$OUTPUT_DATE_FORMAT")

  echo "$MONDAY_IN_REQUESTED_WEEK"
  echo "$TUESDAY_IN_REQUESTED_WEEK"
  echo "$WEDNESDAY_IN_REQUESTED_WEEK"
  echo "$THURSDAY_IN_REQUESTED_WEEK"
  echo "$FRIDAY_IN_REQUESTED_WEEK"
  echo "$SATURDAY_IN_REQUESTED_WEEK"
  echo "$SUNDAY_IN_REQUESTED_WEEK"
}

function removeLeadingZero() {
    WEEKNUMBER=$1
    echo "$1" | sed -e 's/^0//g'
}

function showday(){
  DAY=$1
  OPTIONS=$2
  #echo ">$DAY<"
  EPOCHE=$($DATEUTIL -d"${DAY}T00:00:00" "+%s")
  if [ $EPOCHE -lt $($DATEUTIL -d"$($DATEUTIL +%F)T00:00:00" +%s) ]
  then
    tput setaf 6
    $DATEUTIL -d"$DAY" "+%m-%d %a"
    task rc.color:off $CONFIG_OPTIONS sch:$DAY $OPTIONS $TASKW_REPORT
    tput sgr0
  else
    DAY_OF_WEEK=$($DATEUTIL -d"$DAY" "+%w")
    if [ "$DAY" = "$($DATEUTIL +%F)" ]
    then
      if [ $COLORS -eq 1 ]; then
        tput setaf 2
        tput bold
      fi
      $DATEUTIL -d"$DAY" "+%m-%d %a"
      if [ $COLORS -eq 1 ]; then
        tput sgr0
      fi
    elif [ $DAY_OF_WEEK -eq 6 ] || [ $DAY_OF_WEEK -eq 0 ]
    then
      if [ $COLORS -eq 1 ]; then
        tput setaf 1
      fi
      $DATEUTIL -d"$DAY" "+%m-%d %a"
      if [ $COLORS -eq 1 ]; then
        tput sgr0
      fi
    else
      if [ $COLORS -eq 1 ]; then
        tput setaf 2
      fi
      $DATEUTIL -d"$DAY" "+%m-%d %a"
      if [ $COLORS -eq 1 ]; then
        tput sgr0
      fi
    fi
    if [ $COLORS -eq 1 ]; then
      task $CONFIG_OPTIONS sch:$DAY $OPTIONS $TASKW_REPORT
    else
      task rc.color:off $CONFIG_OPTIONS sch:$DAY $OPTIONS $TASKW_REPORT
    fi
  fi
}

function showweek(){
  WEEK=$1
  OPTIONS=$2
  echo "Week:  $WEEK"
  task $CONFIG_OPTIONS week:$WEEK sch: $OPTIONS $TASKW_REPORT
  WEEK_DAYS=$(getDaysOfWeek $WEEK)
  for DAY in $WEEK_DAYS
  do
    showday $DAY $OPTIONS
  done
}

# add before after weeknumber date option
function getOptions() {
  while getopts "r:" options; do
    case $options in
      r )
        TASKW_REPORT="$OPTARG"
        ;;
      \? )
        exit 1
        ;;
    esac
  done
  PARSED_OPT_COUNT=$OPTIND
}

DATEUTIL=$(setDateUtil)

#CONFIG_OPTIONS="rc.verbose:nothing rc.indent.report:7 rc.column.padding:2 rc.color:off"
#CONFIG_OPTIONS="rc.verbose:label rc.indent.report:7"
CONFIG_OPTIONS="rc.verbose:nothing rc.indent.report:9 rc.dateformat:Y-M-D"

OPTIONS=""
: ${TASKW_REPORT:="cal"}
: ${COLORS:=1}
getOptions $@
shift $(( PARSED_OPT_COUNT - 1 ));

if [ "$#" -ge 1 ]; then

  if [ "$1" = "finished" ];then
    TASKW_REPORT=finished
    COLORS=0
    shift
  fi

  if [ $(echo "$1" | grep "^[0-9]*$") ]; then
    WEEK=$(removeLeadingZero $1)
    shift
    OPTIONS=$@
    showweek $WEEK $OPTIONS
  elif [ $(echo "$1" | grep "^\(+\|-\)[0-9]*$") ]; then
    CURRENT_WEEK=$(removeLeadingZero $(date +%V))
    WEEK_INCREMENT=$( echo "$1" | sed -e 's/\+//g' -e 's/-//g')
    WEEK_INCREMENT_SIGN=$( echo "$1" | sed 's/[0-9]*//g' )
    shift
    OPTIONS=$@
    if [ "$WEEK_INCREMENT_SIGN" = "-" ] && [ -n "$WEEK_INCREMENT" ]; then
      for (( I=$WEEK_INCREMENT; I>0; I-- )); do
        WEEK=$(( CURRENT_WEEK - I ))
        showweek $(removeLeadingZero $WEEK) $OPTIONS
      done
    fi
    showweek $CURRENT_WEEK $OPTIONS
    if [ "$WEEK_INCREMENT_SIGN" = "+" ] && [ -n "$WEEK_INCREMENT" ]; then
      for (( I=1; I<=$WEEK_INCREMENT; I++ )); do
        WEEK=$(( CURRENT_WEEK + I ))
        showweek $(removeLeadingZero $WEEK) $OPTIONS
      done
    fi
  elif [ $(echo "$1" | grep "^[0-9]*\(,[0-9]*\)\{1,\}$") ]; then
    WEEKS=$(echo "$1" | tr ',' '\n')
    shift
    OPTIONS=$@
    for WEEK in $WEEKS
    do
      showweek $(removeLeadingZero $WEEK) $OPTIONS
    done
  elif [ $(echo "$1" | grep "^\(+\|-\)[0-9]*\(,\(+\|-\)[0-9]*\)\{1,\}$") ]; then
    WEEK_INCREMENTS=$(echo "$1" | tr ',' '\n')
    shift
    OPTIONS=$@
    CURRENT_WEEK=$(removeLeadingZero $(date +%V))
    for INCREMENT in $WEEK_INCREMENTS
    do
      WEEK=$(( CURRENT_WEEK + INCREMENT ))
      showweek $WEEK $OPTIONS
    done
  elif [ $(echo "$1" | grep "^\([0-9][0-9]\)*[0-9]\{2\}-[0-9]\{2\}-[0-9]\{2\}$") ]; then
    DAY=$($DATEUTIL -d"$1" +%F)
    shift
    OPTIONS=$@
    showday $DAY $OPTIONS
  elif [ "$1" = "today" ]; then
    DAY=$($DATEUTIL +%F)
    shift
    OPTIONS=$@
    showday $DAY $OPTIONS
  elif [[ "$1" == ad* ]] || [[ "$1" == de* ]] || [[ "$1" == mo* ]] || [[ "$1" == an* ]] || [[ "$1" == ap* ]] || [[ "$1" == ed* ]] ||  [[ "$1" == do* ]] || [[ "$1" == du* ]]
  then
    echo "do not use modifying commands in calendar view !"
  else
    WEEK=$(removeLeadingZero $(date +%V))
    OPTIONS=$@
    showweek $WEEK $OPTIONS
  fi
else
  WEEK=$(removeLeadingZero $(date +%V))
  showweek $WEEK ""
fi

